[git]
filter_commits = true
tag_pattern = "v[0-9].*"

[cli]
output = "CHANGELOG.md"

[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n"

[commit_types]
feat = { changelog_title = "ğŸš€ Features" }
fix = { changelog_title = "ğŸ› Bug Fixes" }
refactor = { changelog_title = "ğŸ”¨ Refactoring" }
perf = { changelog_title = "âš¡ Performance Improvements" }
docs = { changelog_title = "ğŸ“š Documentation" }
chore = { changelog_title = "ğŸ§¹ Maintenance" }